---
diasalsa: 
  version: 0.0.0
  required: false
  description: >
    Proxy interface to DIA Salsa's Actions tool
  homeable: false
  tables: 
    diasalsa_actions: |
      
      action_id I4 PRIMARY,
      key_id I4 UNIQUE,
      content_id I4 NOTNULL,
      expire_date I4,
      thankyou_data X
      CONSTRAINT '
      , CONSTRAINT `diasalsa_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)'
      
    diasalsa_action_content_map: |
      
      content_id I4 PRIMARY,
      action_c_key_id I4 NOTNULL,
      action_c_detail_key_id I4 NOTNULL
      CONSTRAINT '
      , CONSTRAINT `diasalsa_action_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)'
      
    diasalsa_action_cnxn_map: |
      
      to_content_id I4 PRIMARY,
      action_content_id I4 NOTNULL
      CONSTRAINT '
      , CONSTRAINT `dissalsa_action_cnxn_a_c_id_ref` FOREIGN KEY (`action_content_id`) REFERENCES `liberty_content` (`content_id`)
      , CONSTRAINT `diasalsa_action_cnxn_to_c_id_ref` FOREIGN KEY (`to_content_id`) REFERENCES `liberty_content` (`content_id`)'
      
    diasalsa_track: |
      
      action_id I4 NOTNULL,
      email C(200) NOTNULL
      CONSTRAINT '
      , CONSTRAINT `diasalsa_track_ref` FOREIGN KEY (`action_id`) REFERENCES `diasalsa_actions` (`action_id`)'
      
  sequences: 
    diasalsa_action_id_seq: 
      start: 1
  permissions: 
    p_actions_create: 
      description: Can create a action
      level: registered
    p_actions_update: 
      description: Can update actions
      level: editors
    p_actions_view: 
      description: Can read actions
      level: basic
    p_actions_admin: 
      description: Can admin actions
      level: admin
